scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/filesystem/posix',
    'src/jvm/fr/cnrs/liris/accio/core/filesystem/s3',
    '3rdparty/jvm/com/twitter/inject:app',
  ],
  sources=globs('*.scala')
)