scala_library(
  dependencies=[
    '3rdparty/jvm/com/twitter/util:core',
    '3rdparty/jvm/com/typesafe/scala-logging',
  ],
  sources=globs('*.scala')
)

scala_library(
  name='annotations',
  dependencies=[
    '3rdparty/jvm/com/twitter/inject:core',
  ],
  sources=globs('*.java')
)