scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/scheduler',
    'src/jvm/fr/cnrs/liris/accio/scheduler/standalone',
    '3rdparty/jvm/com/twitter/inject:core',
  ],
  sources=globs('*.scala')
)
