scala_library(
  dependencies=[
    ':annotations',
    'src/jvm/fr/cnrs/liris/accio/core/dsl',
    '3rdparty/jvm:scala-guice',
  ],
  sources=globs('*.scala')
)

scala_library(
  name='annotations',
  sources=globs('*.java')
)