# Accio is a platform to launch computer science experiments.
# Copyright (C) 2016-2018 Vincent Primault <v.primault@ucl.ac.uk>
#
# Accio is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Accio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Accio.  If not, see <http://www.gnu.org/licenses/>.

workspace(name = "org_accio")

## Download and load the rules bringing Scala support.
# https://github.com/bazelbuild/rules_scala
rules_scala_version = "21c8913a2cf35130870df9f07a781afc77f33693"
http_archive(
  name = "io_bazel_rules_scala",
  url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % rules_scala_version,
  type = "zip",
  strip_prefix= "rules_scala-%s" % rules_scala_version
)

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

load("@io_bazel_rules_scala//twitter_scrooge:twitter_scrooge.bzl", "twitter_scrooge")
twitter_scrooge()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")
scala_register_toolchains()

## Download and load the rules bringing Node support.
# https://github.com/bazelbuild/rules_node
rules_node_version = "8c11abc21a96a5305004307e3d98f1d05985ac75"
http_archive(
  name = "build_bazel_rules_nodejs",
  url = "https://github.com/bazelbuild/rules_nodejs/archive/%s.zip" % rules_node_version,
  type = "zip",
  strip_prefix= "rules_nodejs-%s" % rules_node_version
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")
node_repositories(package_json = ["//3rdparty:package.json"])

## Load Maven dependencies.
# Dependencies are automatically generated by the `./bin/bazel-deps` script.
load("//3rdparty/jvm:workspace.bzl", "maven_dependencies")
maven_dependencies()

# Update to a more recent Scrooge version.
bind(name = 'io_bazel_rules_scala/dependency/thrift/scrooge_core', actual = '//3rdparty/jvm/com/twitter:scrooge_core')
bind(name = 'io_bazel_rules_scala/dependency/thrift/scrooge_generator', actual = '//3rdparty/jvm/com/twitter:scrooge_generator')

## Download and load the rules bringing Docker support.
# https://github.com/bazelbuild/rules_docker
rules_docker_version = "4d8ec6570a5313fb0128e2354f2bc4323685282a"
http_archive(
  name = "io_bazel_rules_docker",
  url = "https://github.com/bazelbuild/rules_docker/archive/%s.zip" % rules_docker_version,
  type = "zip",
  strip_prefix= "rules_docker-%s" % rules_docker_version
)

load("@io_bazel_rules_docker//scala:image.bzl", scala_image_repositories = "repositories")
scala_image_repositories()
