junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/ops/clustering',
    'test/jvm/fr/cnrs/liris/accio/ops/testing',
    'test/jvm/fr/cnrs/liris/testing',
  ],
  sources=globs('*.scala'),
)
