scala_library(
  dependencies=[
    'src/thrift/fr/cnrs/liris/accio/api',
  ],
  sources=globs('*.scala')
)

scala_library(
  name='annotations',
  dependencies=[
    '3rdparty/jvm/com/twitter/inject:core',
  ],
  sources=globs('*.java')
)