scala_library(
  dependencies=[
    'src/thrift/fr/cnrs/liris/accio/framework/api',
  ],
  sources=globs('*.scala')
)

scala_library(
  name='annotations',
  dependencies=[
    '3rdparty/jvm/com/google/guice',
  ],
  sources=globs('*.java')
)