scala_library(
  name='archiver',
  dependencies=[
    '3rdparty/jvm/org/apache/commons/compress',
    '3rdparty/jvm/com/google/guava',
  ],
  sources=['Archiver.scala']
)


java_library(
  name='annotations',
  dependencies=[
    '3rdparty/jvm/com/google/guice',
  ],
  sources=globs('*.java')
)