scala_library(
  dependencies=[
    'src/thrift/fr/cnrs/liris/accio/framework/api',
    'src/jvm/fr/cnrs/liris/accio/framework/storage',
    '3rdparty/jvm/com/twitter/inject:app',
  ],
  sources=globs('*.scala')
)
