scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/downloader',
    'src/jvm/fr/cnrs/liris/accio/core/downloader/getter',
    '3rdparty/jvm:scala-guice',
  ],
  sources=globs('*.scala')
)