junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/privamov/core/clustering',
    'test/jvm/fr/cnrs/liris/privamov/testing',
    'test/jvm/fr/cnrs/liris/testing',
  ],
  sources=globs('*.scala'),
)
