junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/framework/filesystem/archive',
    'test/jvm/fr/cnrs/liris/testing',
    'test/resources/fr/cnrs/liris/accio/framework/filesystem/archive',
  ],
  sources=globs('*.scala'),
)
