scala_library(
  dependencies=[
    '3rdparty/jvm:scala-time',
    'src/jvm/fr/cnrs/liris/privamov/core/model',
    'src/jvm/fr/cnrs/liris/privamov/core/io',
    'src/jvm/fr/cnrs/liris/common/geo',
  ],
  resources = [
    'test/resources/fr/cnrs/liris/privamov/testing',
  ],
  sources=globs('*.scala'),
)
