scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/storage/elastic',
    'src/jvm/fr/cnrs/liris/accio/core/storage/local',
    '3rdparty/jvm/com/twitter/inject:app',
  ],
  sources=globs('*.scala')
)