scala_library(
  dependencies=[
    'src/thrift/fr/cnrs/liris/accio/core/domain',
    'src/jvm/fr/cnrs/liris/accio/core/statemgr',
  ],
  sources=globs('*.scala')
)

java_library(
  name='annotations',
  dependencies=[
    '3rdparty/jvm/com/google/guice',
  ],
  sources=globs('*.java')
)