scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/dal/core/api',
    'src/jvm/fr/cnrs/liris/dal/core/sparkle',
    'src/jvm/fr/cnrs/liris/dal/core/io',
  ],
  sources=globs('*.scala')
)

java_library(
  name='annotations',
  sources=globs('*.java')
)