scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/api/sparkle',
    'src/jvm/fr/cnrs/liris/accio/core/api/io',
  ],
  sources=globs('*.scala')
)

java_library(
  name='annotations',
  sources=globs('*.java')
)