scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/dal/core/api',
    #'src/jvm/fr/cnrs/liris/accio/core/operator',
    'src/thrift/fr/cnrs/liris/accio/core/api',
  ],
  sources=globs('*.scala')
)