scala_library(
    name='param',
    dependencies=[
        ':annotations',
        'src/jvm/fr/cnrs/liris/common/reflect',
        'src/jvm/fr/cnrs/liris/common/random',
        'src/jvm/fr/cnrs/liris/common/geo',
        '3rdparty/jvm/twitter/util:core',
    ],
    sources=globs('*.scala')
)

java_library(
    name='annotations',
    sources=globs('*.java')
)