junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/filesystem/archive',
    'test/jvm/fr/cnrs/liris/testing',
  ],
  resources = [
    'test/resources/fr/cnrs/liris/accio/core/filesystem/archive',
  ],
  sources=globs('*.scala'),
)