scala_library(
  dependencies=[
    'src/thrift/fr/cnrs/liris/accio/core/domain',
    'src/jvm/fr/cnrs/liris/accio/core/storage',
    '3rdparty/jvm/com/google/guice',
  ],
  sources=globs('*.scala')
)
