junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/statemgr/zookeeper',
    'test/jvm/fr/cnrs/liris/accio/core/statemgr',
    '3rdparty/jvm/org/apache/curator:test',
  ],
  sources=globs('*.scala'),
)