scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/scheduler',
    'src/jvm/fr/cnrs/liris/accio/core/scheduler/standalone',
    '3rdparty/jvm/com/twitter/inject:app',
  ],
  sources=globs('*.scala')
)
