scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/client/service',
    'src/jvm/fr/cnrs/liris/accio/core/infra/cli:annotations',
    'src/jvm/fr/cnrs/liris/accio/core/infra/cli',
    'src/jvm/fr/cnrs/liris/accio/core/domain',
    'src/thrift/fr/cnrs/liris/accio/agent',

    'src/jvm/fr/cnrs/liris/common/util',
    '3rdparty/jvm/com/typesafe/scala-logging',
    '3rdparty/jvm/com/twitter/finatra:jackson',
    '3rdparty/jvm/org/ocpsoft/prettytime',
    '3rdparty/jvm:scala-guice',
  ],
  sources=globs('*.scala')
)