scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/common/cli:annotations',
    'src/jvm/fr/cnrs/liris/common/cli',
    'src/jvm/fr/cnrs/liris/accio/client/config',
    'src/jvm/fr/cnrs/liris/accio/core/domain',
    'src/jvm/fr/cnrs/liris/accio/core/analysis',
    'src/jvm/fr/cnrs/liris/accio/core/util',
    'src/thrift/fr/cnrs/liris/accio/agent',

    'src/jvm/fr/cnrs/liris/common/util',
    '3rdparty/jvm/com/typesafe/scala-logging',
    '3rdparty/jvm/org/ocpsoft/prettytime',
    '3rdparty/jvm:scala-guice',
  ],
  sources=globs('*.scala')
)