scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/framework/filesystem',
    'src/jvm/fr/cnrs/liris/common/util',
    '3rdparty/jvm/org/apache/commons/compress',
    '3rdparty/jvm/com/google/guava',
  ],
  sources=globs('*.scala')
)


