java_library(
  name = 'geometry',
  srcs = glob(["*.java"]),
  deps = [
    '//3rdparty/jvm/com/google/guava',
    '//3rdparty/jvm/com/google/code/findbugs:jsr305',
  ],
  visibility = ["//visibility:public"],
)
