junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/agent/handler',
    'test/jvm/fr/cnrs/liris/testing',
    '3rdparty/jvm/com/twitter/util:core',
  ],
  resources = [
    'test/resources/fr/cnrs/liris/accio/agent/handler:dummy_executor',
  ],
  sources=globs('*.scala'),
)