scala_library(
  name='elastic',
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/domain',
    'src/jvm/fr/cnrs/liris/accio/core/application',

    '3rdparty/jvm/org/elasticsearch:client',
    '3rdparty/jvm/com/twitter/finatra:jackson',
    '3rdparty/jvm/com/typesafe/scala-logging',
    '3rdparty/jvm:scala-guice',
    '3rdparty/jvm/com/google/guava',
  ],
  sources=globs('*.scala')
)