junit_tests(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/core/dsl',
    'src/jvm/fr/cnrs/liris/accio/core/storage/memory',
    'test/jvm/fr/cnrs/liris/testing',
  ],
  sources=globs('*.scala'),
)