scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/storage/elastic',
    'src/jvm/fr/cnrs/liris/accio/storage/memory',
    '3rdparty/jvm/com/twitter/inject:core',
  ],
  sources=globs('*.scala')
)