scala_library(
  dependencies=[
    'src/jvm/fr/cnrs/liris/accio/framework/storage/elastic',
    'src/jvm/fr/cnrs/liris/accio/framework/storage/memory',
    '3rdparty/jvm/com/twitter/inject:app',
  ],
  sources=globs('*.scala')
)