scala_library(
  name='testing',
  dependencies=[
    'src/jvm/fr/cnrs/liris/common/util',
    '3rdparty/jvm:junit',
    '3rdparty/jvm:scalatest',
    scoped('3rdparty/jvm:logback', 'runtime'),
  ],
  sources=globs('*.scala')
)